# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
import numpy as np

In [7]:
# 1.Crear un arreglo de ceros de longitud 12
arreglo_ceros = np.zeros(12)
print(arreglo_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
# 2.Crear un arreglo de longitud 10 con ceros en todas sus posiciones
arreglo = np.zeros(10)

# Asignar el valor 10 a la posición número 5 (índice 4)
arreglo[4] = 10
print(arreglo)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [11]:
# 3.Crear un arreglo que tenga los números del 10 al 49.
arreglo = np.arange(10, 50)
print(arreglo)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
# 4.Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8.
lista = [[0,1,2],[3,4,5],[6,7,8]]
arr2d = np.array(lista)
print(arr2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
# Chequeo pto 4.
print(arr2d.ndim)

2


In [22]:
# 5.Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
numeros_aleatorios = np.random.rand(100)
# Calcular la media y la varianza
media = np.mean(numeros_aleatorios)
varianza = np.var(numeros_aleatorios)
print("Media:", media)
print("Varianza:", varianza)

Media: 0.5236371191865352
Varianza: 0.083790335180522


In [27]:
# 6.Calcular la media de un arreglo usando np.sum
nuevo_arreglo = np.array([1, 2, 3, 4, 5])
# Calcular la suma de los elementos del arreglo
suma_total = np.sum(nuevo_arreglo)
# Calcular la media dividiendo la suma total entre la longitud del arreglo
media = suma_total / nuevo_arreglo.size
print("Media del arreglo:", media)

Media del arreglo: 3.0


In [40]:
# Chequeo pto 6.
nuevo_arreglo = np.array([1, 2, 3, 4, 5])
suma_total = np.sum(nuevo_arreglo)
print(suma_total)

15


In [44]:
# 7.Calcular la varianza de un arreglo usando np.sum y np.mean
# Varianza = Sumatoria ((xi - xmed)^2)/n 

nuevo_arreglo2 = np.array([6, 7, 8, 9, 10])

# Paso 1: Calcular la media del arreglo
media = np.mean(nuevo_arreglo2)

# Paso 2: Restar la media de cada elemento del arreglo
diferencias = nuevo_arreglo2 - media

# Paso 3: Elevar al cuadrado cada diferencia
diferencias_cuadradas = diferencias ** 2

# Paso 4: Sumar todos los cuadrados de las diferencias
suma_cuadrados = np.sum(diferencias_cuadradas)

# Paso 5: Dividir esta suma por la longitud del arreglo para obtener la varianza
varianza = suma_cuadrados / nuevo_arreglo2.size

print("Varianza del arreglo:", varianza)

Varianza del arreglo: 2.0


In [45]:
# Chequeo pto 7.
nuevo_arreglo2 = np.array([6, 7, 8, 9, 10])
media = np.mean(nuevo_arreglo2)
print(media)

8.0


In [51]:
# Chequeo pto 7.
diferencias = nuevo_arreglo2 - media
print(diferencias)

[-2. -1.  0.  1.  2.]


In [49]:
# Chequeo pto 7.
diferencias_cuadradas = diferencias ** 2
print (diferencias_cuadradas)

[4. 1. 0. 1. 4.]


In [50]:
# Chequeo pto 7.
suma_cuadrados = np.sum(diferencias_cuadradas)
print (suma_cuadrados)

10.0


In [52]:
# 8. Crear un array de números aleatorios usando np.random.randn.
arreglo_aleatorio = np.random.randn(10)
print("Array de números aleatorios:")
print(arreglo_aleatorio)

Array de números aleatorios:
[ 0.40186013 -1.09747535 -0.12097283 -0.80487051  0.67927055 -0.96381771
  1.93662242 -0.99114494  0.42775159 -1.64219187]
